main: laxer.Main
name: Core
version: 1.0
author: NEOZ04
description: The Core Plugin For Laxer Network
commands:
    spawn:
      description: Back to spawn
      usage: /spawn
    wt:
      description: World teleport
      usage: /wt <world_name>
    test:
      description: An example command
      usage: /test
      permission: laxer.test
      permission-message: You don't have the laxer.test permission.